package dao;

import model.BicycleOrderDetail;

public interface BicycleOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_order_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_order_detail
     *
     * @mbggenerated
     */
    int insert(BicycleOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_order_detail
     *
     * @mbggenerated
     */
    int insertSelective(BicycleOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_order_detail
     *
     * @mbggenerated
     */
    BicycleOrderDetail selectByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BicycleOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BicycleOrderDetail record);
}