package dao;

import model.BicycleOrder;

public interface BicycleOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_order
     *
     * @mbggenerated
     */
    int insert(BicycleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_order
     *
     * @mbggenerated
     */
    int insertSelective(BicycleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_order
     *
     * @mbggenerated
     */
    BicycleOrder selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BicycleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BicycleOrder record);
}