package model;

import java.util.List;

/**
 * 车辆订单类
 */
public class BicycleOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order.ORDER_ID
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order.ORDER_CODE
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order.VENDER_ID
     *
     * @mbggenerated
     */
    private Integer venderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order.BUY_DATE
     *
     * @mbggenerated
     */
    private String buyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order.BUY_NUM
     *
     * @mbggenerated
     */
    private Double buyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order.BUY_PRICE
     *
     * @mbggenerated
     */
    private Double buyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order.PERSON_IN_CHARGE
     *
     * @mbggenerated
     */
    private String personInCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order.INVOICE_NO
     *
     * @mbggenerated
     */
    private String invoiceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order.USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order.OPERATOR_TIME
     *
     * @mbggenerated
     */
    private String operatorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order.ORDER_ID
     *
     * @return the value of bicycle_order.ORDER_ID
     *
     * @mbggenerated
     */
    /**
     *订单中的详细信息表,不止一条,作为list放入订单类中,
     */
    private List<BicycleOrderDetail> bicycleOrderDetails;


    public List<BicycleOrderDetail> getBicycleOrderDetails() {
        return bicycleOrderDetails;
    }

    public void setBicycleOrderDetails(List<BicycleOrderDetail> bicycleOrderDetails) {
        this.bicycleOrderDetails = bicycleOrderDetails;
    }

    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order.ORDER_ID
     *
     * @param orderId the value for bicycle_order.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order.ORDER_CODE
     *
     * @return the value of bicycle_order.ORDER_CODE
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order.ORDER_CODE
     *
     * @param orderCode the value for bicycle_order.ORDER_CODE
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order.VENDER_ID
     *
     * @return the value of bicycle_order.VENDER_ID
     *
     * @mbggenerated
     */
    public Integer getVenderId() {
        return venderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order.VENDER_ID
     *
     * @param venderId the value for bicycle_order.VENDER_ID
     *
     * @mbggenerated
     */
    public void setVenderId(Integer venderId) {
        this.venderId = venderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order.BUY_DATE
     *
     * @return the value of bicycle_order.BUY_DATE
     *
     * @mbggenerated
     */
    public String getBuyDate() {
        return buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order.BUY_DATE
     *
     * @param buyDate the value for bicycle_order.BUY_DATE
     *
     * @mbggenerated
     */
    public void setBuyDate(String buyDate) {
        this.buyDate = buyDate == null ? null : buyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order.BUY_NUM
     *
     * @return the value of bicycle_order.BUY_NUM
     *
     * @mbggenerated
     */
    public Double getBuyNum() {
        return buyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order.BUY_NUM
     *
     * @param buyNum the value for bicycle_order.BUY_NUM
     *
     * @mbggenerated
     */
    public void setBuyNum(Double buyNum) {
        this.buyNum = buyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order.BUY_PRICE
     *
     * @return the value of bicycle_order.BUY_PRICE
     *
     * @mbggenerated
     */
    public Double getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order.BUY_PRICE
     *
     * @param buyPrice the value for bicycle_order.BUY_PRICE
     *
     * @mbggenerated
     */
    public void setBuyPrice(Double buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order.PERSON_IN_CHARGE
     *
     * @return the value of bicycle_order.PERSON_IN_CHARGE
     *
     * @mbggenerated
     */
    public String getPersonInCharge() {
        return personInCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order.PERSON_IN_CHARGE
     *
     * @param personInCharge the value for bicycle_order.PERSON_IN_CHARGE
     *
     * @mbggenerated
     */
    public void setPersonInCharge(String personInCharge) {
        this.personInCharge = personInCharge == null ? null : personInCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order.INVOICE_NO
     *
     * @return the value of bicycle_order.INVOICE_NO
     *
     * @mbggenerated
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order.INVOICE_NO
     *
     * @param invoiceNo the value for bicycle_order.INVOICE_NO
     *
     * @mbggenerated
     */
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo == null ? null : invoiceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order.USER_ID
     *
     * @return the value of bicycle_order.USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order.USER_ID
     *
     * @param userId the value for bicycle_order.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order.OPERATOR_TIME
     *
     * @return the value of bicycle_order.OPERATOR_TIME
     *
     * @mbggenerated
     */
    public String getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order.OPERATOR_TIME
     *
     * @param operatorTime the value for bicycle_order.OPERATOR_TIME
     *
     * @mbggenerated
     */
    public void setOperatorTime(String operatorTime) {
        this.operatorTime = operatorTime == null ? null : operatorTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order.REMARK
     *
     * @return the value of bicycle_order.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order.REMARK
     *
     * @param remark the value for bicycle_order.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order.STATUS
     *
     * @return the value of bicycle_order.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order.STATUS
     *
     * @param status the value for bicycle_order.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}