package model;

public class BicycleOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order_detail.DETAIL_ID
     *
     * @mbggenerated
     */
    private Integer detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order_detail.CATAGORY_ID
     *
     * @mbggenerated
     */
    private Integer catagoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order_detail.ORDER_ID
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order_detail.BICYCLE_ID
     *
     * @mbggenerated
     */
    private Integer bicycleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order_detail.CREATE_DATE
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order_detail.BATCH_NO
     *
     * @mbggenerated
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order_detail.PRICE
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_order_detail.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order_detail.DETAIL_ID
     *
     * @return the value of bicycle_order_detail.DETAIL_ID
     *
     * @mbggenerated
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order_detail.DETAIL_ID
     *
     * @param detailId the value for bicycle_order_detail.DETAIL_ID
     *
     * @mbggenerated
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order_detail.CATAGORY_ID
     *
     * @return the value of bicycle_order_detail.CATAGORY_ID
     *
     * @mbggenerated
     */
    public Integer getCatagoryId() {
        return catagoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order_detail.CATAGORY_ID
     *
     * @param catagoryId the value for bicycle_order_detail.CATAGORY_ID
     *
     * @mbggenerated
     */
    public void setCatagoryId(Integer catagoryId) {
        this.catagoryId = catagoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order_detail.ORDER_ID
     *
     * @return the value of bicycle_order_detail.ORDER_ID
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order_detail.ORDER_ID
     *
     * @param orderId the value for bicycle_order_detail.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order_detail.BICYCLE_ID
     *
     * @return the value of bicycle_order_detail.BICYCLE_ID
     *
     * @mbggenerated
     */
    public Integer getBicycleId() {
        return bicycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order_detail.BICYCLE_ID
     *
     * @param bicycleId the value for bicycle_order_detail.BICYCLE_ID
     *
     * @mbggenerated
     */
    public void setBicycleId(Integer bicycleId) {
        this.bicycleId = bicycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order_detail.CREATE_DATE
     *
     * @return the value of bicycle_order_detail.CREATE_DATE
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order_detail.CREATE_DATE
     *
     * @param createDate the value for bicycle_order_detail.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order_detail.BATCH_NO
     *
     * @return the value of bicycle_order_detail.BATCH_NO
     *
     * @mbggenerated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order_detail.BATCH_NO
     *
     * @param batchNo the value for bicycle_order_detail.BATCH_NO
     *
     * @mbggenerated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order_detail.PRICE
     *
     * @return the value of bicycle_order_detail.PRICE
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order_detail.PRICE
     *
     * @param price the value for bicycle_order_detail.PRICE
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_order_detail.REMARK
     *
     * @return the value of bicycle_order_detail.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_order_detail.REMARK
     *
     * @param remark the value for bicycle_order_detail.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}