package model;

public class Vender {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.VENDER_ID
     *
     * @mbggenerated
     */
    private Integer venderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.VENDER_CODE
     *
     * @mbggenerated
     */
    private String venderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.VENDER_TYPE
     *
     * @mbggenerated
     */
    private String venderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.VENDER_NAME
     *
     * @mbggenerated
     */
    private String venderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.TELPHONE
     *
     * @mbggenerated
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.CONTACTS
     *
     * @mbggenerated
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.PRODUCT_LICENSE
     *
     * @mbggenerated
     */
    private String productLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.BUSSINESS_REGISTRATION_NO
     *
     * @mbggenerated
     */
    private String bussinessRegistrationNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.REGISTERED_CAPITAL
     *
     * @mbggenerated
     */
    private Double registeredCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.ZXBJ
     *
     * @mbggenerated
     */
    private String zxbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.VENDER_ID
     *
     * @return the value of vender.VENDER_ID
     *
     * @mbggenerated
     */
    public Integer getVenderId() {
        return venderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.VENDER_ID
     *
     * @param venderId the value for vender.VENDER_ID
     *
     * @mbggenerated
     */
    public void setVenderId(Integer venderId) {
        this.venderId = venderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.VENDER_CODE
     *
     * @return the value of vender.VENDER_CODE
     *
     * @mbggenerated
     */
    public String getVenderCode() {
        return venderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.VENDER_CODE
     *
     * @param venderCode the value for vender.VENDER_CODE
     *
     * @mbggenerated
     */
    public void setVenderCode(String venderCode) {
        this.venderCode = venderCode == null ? null : venderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.VENDER_TYPE
     *
     * @return the value of vender.VENDER_TYPE
     *
     * @mbggenerated
     */
    public String getVenderType() {
        return venderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.VENDER_TYPE
     *
     * @param venderType the value for vender.VENDER_TYPE
     *
     * @mbggenerated
     */
    public void setVenderType(String venderType) {
        this.venderType = venderType == null ? null : venderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.VENDER_NAME
     *
     * @return the value of vender.VENDER_NAME
     *
     * @mbggenerated
     */
    public String getVenderName() {
        return venderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.VENDER_NAME
     *
     * @param venderName the value for vender.VENDER_NAME
     *
     * @mbggenerated
     */
    public void setVenderName(String venderName) {
        this.venderName = venderName == null ? null : venderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.ADDRESS
     *
     * @return the value of vender.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.ADDRESS
     *
     * @param address the value for vender.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.TELPHONE
     *
     * @return the value of vender.TELPHONE
     *
     * @mbggenerated
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.TELPHONE
     *
     * @param telphone the value for vender.TELPHONE
     *
     * @mbggenerated
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.CONTACTS
     *
     * @return the value of vender.CONTACTS
     *
     * @mbggenerated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.CONTACTS
     *
     * @param contacts the value for vender.CONTACTS
     *
     * @mbggenerated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.PRODUCT_LICENSE
     *
     * @return the value of vender.PRODUCT_LICENSE
     *
     * @mbggenerated
     */
    public String getProductLicense() {
        return productLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.PRODUCT_LICENSE
     *
     * @param productLicense the value for vender.PRODUCT_LICENSE
     *
     * @mbggenerated
     */
    public void setProductLicense(String productLicense) {
        this.productLicense = productLicense == null ? null : productLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.BUSSINESS_REGISTRATION_NO
     *
     * @return the value of vender.BUSSINESS_REGISTRATION_NO
     *
     * @mbggenerated
     */
    public String getBussinessRegistrationNo() {
        return bussinessRegistrationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.BUSSINESS_REGISTRATION_NO
     *
     * @param bussinessRegistrationNo the value for vender.BUSSINESS_REGISTRATION_NO
     *
     * @mbggenerated
     */
    public void setBussinessRegistrationNo(String bussinessRegistrationNo) {
        this.bussinessRegistrationNo = bussinessRegistrationNo == null ? null : bussinessRegistrationNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.REGISTERED_CAPITAL
     *
     * @return the value of vender.REGISTERED_CAPITAL
     *
     * @mbggenerated
     */
    public Double getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.REGISTERED_CAPITAL
     *
     * @param registeredCapital the value for vender.REGISTERED_CAPITAL
     *
     * @mbggenerated
     */
    public void setRegisteredCapital(Double registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.USER_ID
     *
     * @return the value of vender.USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.USER_ID
     *
     * @param userId the value for vender.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.CREATE_TIME
     *
     * @return the value of vender.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.CREATE_TIME
     *
     * @param createTime the value for vender.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.ZXBJ
     *
     * @return the value of vender.ZXBJ
     *
     * @mbggenerated
     */
    public String getZxbj() {
        return zxbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.ZXBJ
     *
     * @param zxbj the value for vender.ZXBJ
     *
     * @mbggenerated
     */
    public void setZxbj(String zxbj) {
        this.zxbj = zxbj == null ? null : zxbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.REMARK
     *
     * @return the value of vender.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.REMARK
     *
     * @param remark the value for vender.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}